#!/usr/bin/expect -f


# Configuration

set timeout 20
set host "localhost"
set port "2224"
set user "root"
set pass "12345"

# SSH Connection

spawn ssh -p $port $user@$host
expect "password:"
send "§pass\r"
expect "$ " 

# Commands
set commands {
	"ls -la"
	"cat /etc/passwd"
	"uname -a"
	"whoami"
	"ps aux"
	
}

# loop for commands
foreach cmd $commands {
	puts "\n[>] Sending: $cmd"
	send "$cmd\r"
	expect "$ "
	sleep 1
}

send "exit\r"
expect eof

puts "\n[+] Done"

