#!/usr/bin/expect -f


# Configuration

set timeout 10
set host "localhost"
set port "2224"
set user "root"
set pass "12345"

set iterations 5


for {set i 1} {$i <= $iterations} {incr i} {

# connection to ssh
	spawn ssh -p $port $user@$host
	expect "password:"
	send "§pass\r"
	expect "$ " 

# Commands
	set commands {
		"ls -la"
		"ls"
		"cat /etc/passwd"
		"uname -a"
		"whoami"
		"ps aux"
	
	}

# loop for commands
	foreach cmd $commands {
		send "$cmd\r"
		expect "$ "
		sleep 1
	}

	send "exit\r"
	expect eof
}

puts "\n Done"

